name: Windows
on:
  release:
    types: [published]
  push:

env:
  # Conan cache environment variables
  CONAN_SYSREQUIRES_MODE: enabled
  CONAN_USER_HOME: "${{ github.workspace }}/conan-cache"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/conan-cache/short"

jobs:
  test:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Release
          - Debug
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: ${{ matrix.compiler }}
          build_type: ${{ matrix.build_type }}
          generator: ${{ matrix.generator }}
      - name: Configure CMake
        run: cmake -S . -B ./build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE:STRING=${{matrix.build_type}} -DCOVERAGE_NOTES_WARNINGS_AS_ERRORS:BOOL=ON
      - name: Build
        run: cmake --build ./build --config ${{matrix.build_type}}

      - name: Windows - Test and coverage
        if: runner.os == 'Windows'
        working-directory: ./build
        run: |
          ctest -C ${{matrix.build_type}} --output-on-failure
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.build_type == 'Release' }}
        with:
          files: |
            build/src/${{matrix.build_type}}/coverage-notes-*